### PR TITLE
fix: clear dataset and result state

### LINKED ISSUE #66: Clear state when exiting single algorithm, dataset, result views
If the state is not cleared before exiting a view page, the next time the page is accessed with a different id, it will display the previous one before.

### PR DESCRIPTION
**Pull request by pyphilia**
close #66

### CODE REVIEW

File: src/reducers/resultReducer.js [hunk 1]
```diff
@@ -8,6 +8,7 @@ import {
   FLAG_EXPORTING_RESULT,
   FLAG_DELETING_RESULT,
   EXECUTE_PYTHON_ALGORITHM_SUCCESS,
+  CLEAR_RESULT_SUCCESS,
 } from '../shared/types';
 
 const INITIAL_STATE = Map({
```
Comment (pyphilia) [inline src/reducers/resultReducer.js:14]: Add flag.

**Review by hagoptaminian — APPROVED** [review]
looks good to me!

**Review by Painguin — CHANGES_REQUESTED** [review]
Looks good! I've been a lot more minimalist when clearing the state of algorithms (without flags/try-catch). Could you please add the missing things in clearAlgorithm to be consistent.

**Review by Painguin — APPROVED** [review]
